### PR TITLE
Fix Google Maps Api V3 

### PR DESCRIPTION
**Pull request by videmort**
ionic://* is not valid for google maps with security even if ionic://* is enabled on google cloud console.

Serving the app on httpsionic://* works perfect.

Also https://ionic or http://ionic is not a valid scheme

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I've made the scheme configurable instead of hardcoding to ionic or httpsionic, will be available in next release.

**Comment by cnpallares** [comment]
> ionic://* is not valid for google maps with security even if ionic://* is enabled on google cloud console.
> 
> Serving the app on httpsionic://* works perfect.
> 
> Also https://ionic or http://ionic is not a valid scheme

Hi @videmort ,

Can I ask you for a brief explanation of why httpsionic://* has worked for you?
I have an issue trying to send cookies to the server using WKWebview when cross-origin-requests.
I'm trying some sort of solutions but none worked for me, and am trying to understand how the custom schema works to figure it out if can be a valid solution for me.

Thank you in advance :)

**Comment by videmort** [comment]
Hello @cnpallares

Https:// or http:// is not a valid protocol for iOS

httpsionic:// is just a file://

You can use what you want but not http:// or https://

For example
my custom:// is valid 


In android https:// or http:// is OK

**Comment by manishbhavnani** [comment]
i tried converting it to <preference name="iosScheme" value="httpsionic" /> . the origin was change to  httpsionic .. but still was getting the preflight response.. of preflight not allowed

**Pull request closed without merging**
