### PR TITLE
add _alwaysRunsAtForegroundPriority setting

### LINKED ISSUE #57: New blank app with latest ionic - stuck on splash screen
When I try to run a new blank app that I just created it hangs on splash screen.
Here is  the output in Xcode: 
_objc[26207]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11005a910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x10fded210). One of the two will be used. Which one is undefined.
2017-12-05 23:53:25.714688 MyApp[26207:1446869] subsystem: com.apple.UIKit, category: HIDEventFiltered, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2017-12-05 23:53:25.900011 MyApp[26207:1446869] subsystem: com.apple.UIKit, category: HIDEventIncoming, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2017-12-05 23:53:25.917109 MyApp[26207:1446855] subsystem: com.apple.BaseBoard, category: MachPort, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
2017-12-05 23:53:26.009 MyApp[26207:1446789] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/dennisbutovetsky/Library/Developer/CoreSimulator/Devices/2F159FC2-FC3D-4B98-BA8E-74452F0EA6E5/data/Containers/Data/Application/7BB66E12-8F7E-4244-A826-8E23A02E2FCF/Library/Cookies/io.ionic.starter.binarycookies
2017-12-05 23:53:26.017564 MyApp[26207:1446789] subsystem: com.apple.libsqlite3, category: logging, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2017-12-05 23:53:26.295580 MyApp[26207:1446789] subsystem: com.apple.UIKit, category: StatusBar, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2017-12-05 23:53:26.397 MyApp[26207:1446789] Apache Cordova native platform version 4.3.1 is starting.
2017-12-05 23:53:26.403 MyApp[26207:1446789] Multi-tasking -> Device: YES, App: YES
2017-12-05 23:53:26.437 MyApp[26207:1446789] CDVWKWebViewEngine: trying to inject XHR polyfill
2017-12-05 23:53:26.643549 MyApp[26207:1446789] subsystem: com.apple.UIKit, category: GestureEnvironment, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2017-12-05 23:53:26.644 MyApp[26207:1446789] CDVWKWebViewEngine will reload WKWebView if required on resume
2017-12-05 23:53:26.645 MyApp[26207:1446789] Using Ionic WKWebView
2017-12-05 23:53:26.647 MyApp[26207:1446789] [CDVTimer][handleopenurl] 0.232041ms
2017-12-05 23:53:26.717 MyApp[26207:1446789] [CDVTimer][intentandnavigationfilter] 68.947017ms
2017-12-05 23:53:26.731 MyApp[26207:1446789] [CDVTimer][gesturehandler] 0.446975ms
2017-12-05 23:53:26.746 MyApp[26207:1446789] [CDVTimer][keyboard] 8.565009ms
2017-12-05 23:53:26.912 MyApp[26207:1446789] [CDVTimer][splashscreen] 164.066017ms
2017-12-05 23:53:26.913 MyApp[26207:1446789] [CDVTimer][TotalPluginStartup] 265.953004ms
2017-12-05 23:53:27.148900 MyApp[26207:1446789] subsystem: com.apple.BackBoardServices.fence, category: App, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
2017-12-05 23:54:29.852 MyApp[26207:1446789] Failed to load webpage with error: The request timed out._

Here is my config.xml:

`<content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <allow-navigation href="http://localhost:8080/*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />`

Here is the output of "ionic info":

_cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
    Node       : v6.10.2
    npm        : 3.10.10 
    OS         : OS X El Capitan
    Xcode      : Xcode 8.0 Build version 8A218a 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy_

### PR DESCRIPTION
**Pull request by jacquesdev**
Creating this updated PR on behalf of @ghenry22, since the original #45 had conflicts. (Literally just a copy and paste job)

Closes #45 
Closes #57 

@genry22 - if this has your blessing please comment here so that @mlynch can merge it.

### CODE REVIEW

**Comment by ghenry22** [comment]
I believe you need the keywindow changes from the original PR as well for proper background operation.

**Comment by jacquesdev** [comment]
Hi @ghenry22. I forked the current master, and realised the keywindow changes are already in the project, so no additional changes required.

I guess there was another PR from before where it was added.

Hopefully this PR will save you some time so that you don’t have to resolve conflicts. Thanks for your updates by the way!

**Comment by ghenry22** [comment]
ah right someone already cloned my selectable port PR and included the keywindow settings by the look of it.

**Comment by mlynch** [comment]
Thanks! Merged and the other issue is closed

**Comment by HugoHeneault** [comment]
There also is this PR that might have been missed: https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/58/files :)

**Pull request merged**
