### PR TITLE
iframe loading

### PR DESCRIPTION
**Pull request by cmbilisim**
This patch allow iframes without adding <allow-navigation> in config.xml.

### CODE REVIEW

**Comment by joeldhenry** [comment]
so funny...I came to this same conclusion and found this! can we get this added?

**Comment by nphyatt** [comment]
I'm not sure we want to allow any & all iframes to load without explicitly whitelisting them in some way.

**Comment by cmbilisim** [comment]
> 
> 
> I'm not sure we want to allow any & all iframes to load without explicitly whitelisting them in some way.

On Android, iframes are displayed without any action. I think it would be better if it works the same on the IOS.

**Comment by joeldhenry** [comment]
Have created new pull request https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/585

**Pull request closed without merging**
