### PR TITLE
feat(ios): Add WKSuspendInBackground preference

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by l3ender** [comment]
I'm curious about how this PR works. What are the magic strings for, and why does setting them in `WKWebViewConfiguration` make a difference?

**Comment by heikomat** [comment]
@l3ender As can be determined by the followup lines, these are base64 encoded strings.
The first one decodes to
`alwaysRunsAtForegroundPriority`
and the second one to
`_alwaysRunsAtForegroundPriority`

**Comment by l3ender** [comment]
@heikomat Thanks for the response. Don't know how I missed that (not fluent in Obj C, but still pretty obvious).

Why do the strings need to be encoded?

**Comment by zbarbuto** [comment]
> @l3ender As can be determined by the followup lines, these are base64 encoded strings.
> The first one decodes to
> `alwaysRunsAtForegroundPriority`
> and the second one to
> `_alwaysRunsAtForegroundPriority`

So if Apple ever decides to rename those functions this preference will break again?

**Comment by chrisjdev** [comment]
Isn't this a really bad idea? Looks like there's some details in #286

**Comment by Andrewpk** [comment]
This is a terrible idea. The strings are base64 encoded so Apple's AppStore review scan will generally pass right over them. If Apple finds this, they'll reject and possibly mass-reject/pull any ionic apps using wkwebview.

This should be changed immediately as it is in direct opposition to the AppStore review guidelines.

**Pull request merged**
