### PR TITLE
fix(Android): Handle Range Requests for proper media file handling

### LINKED ISSUE #141: Android 7.0.0+ : Long local video file stuck after first few frames
Hello,

I have some mp4 stored locally which I am using in video tag. If video file length is small (few seconds), then it is working just fine but if length is long then it stuck after first few frames.

Weird part is, It's working fine on 7.0.0 but not on 7.0.0+. (I have tested on 7.1.1 and 8.0. It freezes after few seconds).

Without this plugin installed, everything works just fine.

#### Ionic Info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.1 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.4
    Node              : v6.9.1
    npm               : 3.10.8
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : pro

Help is needed urgently, thanks.

### LINKED ISSUE #205: Videos served from file system thorugh local server are not seekable on android
When using the html5 video tag with a video sotored in the assets, seek is not possible.

Possible cause/fix:
Server does not support "partial content":
`WebViewLocalServer:createWebResourceResponse` uses  `WebViewLocalServer:PathHandler` which always answers with 200 OK instead 206 PartialContent for videos. doing so would allow html5 video player to seek video and load in memory only the desired parts

### LINKED ISSUE #248: Android 5 and 6 do not support playing local music and video
Although convertFileSrc lets you access the local music file to http://localhost:8080, it won't play in android 5 or 6.Clicking the play button does not trigger the shouldInterceptRequest override function in the IonicWebViewEngine class. It is suspected that the returned header file is missing
` var  nativePath_convertFileSrc = _window.Ionic.WebView.convertFileSrc(url_music); `

### PR DESCRIPTION
**Pull request by jcesarmobile**
Properly handle requests with Range header and return appropriate headers so audio and video tags
work correcly and you can go forward or backward ond them

fix #248, fix #205, fix #141

### CODE REVIEW

**Comment by fgilio** [comment]
Thank you @jcesarmobile !

**Comment by lb90** [comment]
Hi! What would be needed to have that on KitKat? Thanks!

**Comment by fgilio** [comment]
🎉

**Pull request merged**
